In [ ]:
import numpy as np
import pandas as pd
from time import time
from IPython.display import display
import helping
import matplotlib.pyplot as plt
from sklearn import cluster
from sklearn.mixture import GaussianMixture as GMM
from sklearn.metrics import silhouette_score

In [ ]:
# Import supplementary visualization code visuals.py
import visuals as vs

# Pretty display for notebooks
%matplotlib inline

# Load the Census dataset
dados = pd.read_csv("resultados.csv")
dados_i = dados.drop(['data'], axis = 1)
dados_i = dados_i.iloc[:896]
dados_i = dados_i.rename(columns = {'concurso': 'number'})
# Success - Display the first record
display(dados_i.iloc[:896].tail(n=200))

In [ ]:
log_data = np.log(pd.DataFrame(dados_i))

In [ ]:
import plotly
from plotly import tools
import plotly.plotly as py
import plotly.graph_objs as go

plotly.tools.set_credentials_file(username='dangstan', api_key='3jrnxeBEjEpRCR4M4oFj')

epsilon = dados_norm['concurso']

N = 100000
trace1 = go.Scattergl(
    x = epsilon,
    y = dados_norm['first'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace2 = go.Scattergl(
    x = epsilon,
    y = dados_norm['sec'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace3 = go.Scattergl(
    x = epsilon,
    y = dados_norm['thi'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace4 = go.Scattergl(
    x = epsilon,
    y = dados_norm['for'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)
trace5 = go.Scattergl(
    x = epsilon,
    y = dados_norm['fif'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)
trace6 = go.Scattergl(
    x = epsilon,
    y = dados_norm['six'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

fig = tools.make_subplots(rows=1, cols=1, shared_xaxes=True, shared_yaxes=True,
                          vertical_spacing=0.001)
fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 1)
fig.append_trace(trace3, 1, 1)
fig.append_trace(trace4, 1, 1)
fig.append_trace(trace5, 1, 1)
fig.append_trace(trace6, 1, 1)

fig['layout'].update(height=1200, width=2000, title='Dados MS')
py.iplot(fig, filename='Dados MS')
#data = [trace]
#py.iplot(data, filename='MS')

In [ ]:
import plotly
from plotly import tools
import plotly.plotly as py
import plotly.graph_objs as go

plotly.tools.set_credentials_file(username='dangstan', api_key='3jrnxeBEjEpRCR4M4oFj')

epsilon = dados['concurso']

N = 100000
trace1 = go.Scattergl(
    x = epsilon,
    y = dados['first'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace2 = go.Scattergl(
    x = epsilon,
    y = dados['sec'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace3 = go.Scattergl(
    x = epsilon,
    y = dados['thi'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace4 = go.Scattergl(
    x = epsilon,
    y = dados['for'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)
trace5 = go.Scattergl(
    x = epsilon,
    y = dados['fif'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)
trace6 = go.Scattergl(
    x = epsilon,
    y = dados['six'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

fig = tools.make_subplots(rows=1, cols=1, shared_xaxes=True, shared_yaxes=True,
                          vertical_spacing=0.001)
fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 1)
fig.append_trace(trace3, 1, 1)
fig.append_trace(trace4, 1, 1)
fig.append_trace(trace5, 1, 1)
fig.append_trace(trace6, 1, 1)

fig['layout'].update(height=1200, width=2000, title='Dados MS')
py.iplot(fig, filename='Dados MS')
#data = [trace]
#py.iplot(data, filename='MS')

In [ ]:
import plotly
from plotly import tools
import plotly.plotly as py
import plotly.graph_objs as go

plotly.tools.set_credentials_file(username='dangstan', api_key='3jrnxeBEjEpRCR4M4oFj')

epsilon = log_dados['concurso']

N = 100000
trace1 = go.Scattergl(
    x = epsilon,
    y = log_dados['first'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace2 = go.Scattergl(
    x = epsilon,
    y = log_dados['sec'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace3 = go.Scattergl(
    x = epsilon,
    y = log_dados['thi'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

trace4 = go.Scattergl(
    x = epsilon,
    y = log_dados['for'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)
trace5 = go.Scattergl(
    x = epsilon,
    y = log_dados['fif'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)
trace6 = go.Scattergl(
    x = epsilon,
    y = log_dados['six'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

fig = tools.make_subplots(rows=1, cols=1, shared_xaxes=True, shared_yaxes=True,
                          vertical_spacing=0.001)
fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 1)
fig.append_trace(trace3, 1, 1)
fig.append_trace(trace4, 1, 1)
fig.append_trace(trace5, 1, 1)
fig.append_trace(trace6, 1, 1)

fig['layout'].update(height=1200, width=2000, title='Dados MS')
py.iplot(fig, filename='Dados MS')
#data = [trace]
#py.iplot(data, filename='MS')

In [ ]:
N = 100000
trace1 = go.Scattergl(
    x = epsilon,
    y = dados['first'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

data1 = [trace1]
py.iplot(data1, filename='MS1')

In [ ]:
N = 100000
trace2 = go.Scattergl(
    x = epsilon,
    y = dados['sec'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

data2 = [trace2]
py.iplot(data2, filename='MS2')

In [ ]:
N = 100000
trace3 = go.Scattergl(
    x = epsilon,
    y = dados['thi'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

data3 = [trace3]
py.iplot(data3, filename='MS3')

In [ ]:
N = 100000
trace4 = go.Scattergl(
    x = epsilon,
    y = dados['for'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

data4 = [trace4]
py.iplot(data4, filename='MS4')

In [ ]:
N = 100000
trace5 = go.Scattergl(
    x = epsilon,
    y = dados['fif'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

data5 = [trace5]
py.iplot(data5, filename='MS5')

In [ ]:
N = 100000
trace6 = go.Scattergl(
    x = epsilon,
    y = dados['six'],
    mode = 'markers',
    marker = dict(
        line = dict(
            width = 1,
            color = '#404040')
    )
)

data6 = [trace6]
py.iplot(data6, filename='MS6')

In [ ]:
bigger = 0.32
dataframe = log_data
for n in range(2,300):   
    for m in range(1,400):
        try:
            
            dbscan = cluster.DBSCAN(eps = n, min_samples = m)
        
            model = dbscan.fit(dataframe[['number', 'first']])
        
            clusterer = dbscan.fit_predict(dataframe[['number', 'first']])

            score = silhouette_score(dataframe[['number', 'first']], clusterer)
            
            if score > bigger:
                print('for n = %d and m = %d' % (n,m))
                print('\033[1m' + str(score) + '\033[0m')
                bigger = score    
            
        except ValueError:
            pass    

In [ ]:
dataframe_2 = dados_i

dataframe_2=((dataframe_2-dataframe_2.min())/(dataframe_2.max()-dataframe_2.min()))
dataframe_2

In [ ]:
from sklearn.mixture import GaussianMixture as GMM
from sklearn.metrics import silhouette_score

for n in range(2,50):

    clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = 200, n_init = 500).fit(dataframe)
        
    preds = clusterer.predict(dataframe)

    centers = clusterer.means_

    score = silhouette_score(dataframe, preds)

    print('for n = %d:' %n)
    print(score)


In [ ]:
from sklearn.mixture import GaussianMixture as GMM
from sklearn.metrics import silhouette_score

p = 0.7
m = 0
for n in range(2,50):
    
        clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = 200, n_init = 500).fit(dataframe_2)
        
        preds = clusterer.predict(dataframe_2)

        centers = clusterer.means_

        score = silhouette_score(dataframe_2, preds)

        if score > p:
            m = n
            p = score
        print('for n = %d:' %n)
        print(score)

In [ ]:
#trying out more variable ranges for one of the desired column labels

data_f=log_data.drop(['sec','thi','for','fif','six'], axis = 1)

doser = 0.05
score = 0.001
sub = 0
bigger = 0.32
for n in range(6,50):
    for m in range(30, 400, 5):
        for j in range(30, 3000, 20):
            clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = m, n_init = j).fit(data_f)

            preds = clusterer.predict(data_f)

            centers = clusterer.means_
            
            doser = score
            
            score = silhouette_score(data_f, preds)

            sub = doser - score
            
            if np.linalg.norm(sub) < 0.02:
                break
        
            if score > bigger:
                print('for n = %d, m = %d and j = %d' % (n,m, j))
                print('\033[1m' + str(score) + '\033[0m')
                bigger = score
            
    print('n = %d' %n)


In [ ]:
data_f=log_dados.drop(['sec','thi','for','fif','six'], axis = 1)

print('best number of clusters: %d' % m)

clusterer = GMM(n_components = m, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_f)
     
preds = clusterer.predict(data_f)

centers = clusterer.means_

score = silhouette_score(data_f, preds)

print(score)

log_data['labels_first']=preds
log_data

In [ ]:
data_s=dataframe.drop(['first','thi','for','fif','six'], axis = 1)

for n in range(2,50):
    
    clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_s)
        
    preds = clusterer.predict(data_s)

    centers = clusterer.means_

    score = silhouette_score(data_s, preds)

    if score > p:
        m = n
        p = score
    print('for n = %d:' %n)
    print(score)

In [ ]:
data_s=dataframe.drop(['first','thi','for','fif','six'], axis = 1)

clusterer = GMM(n_components = m, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_s)
        
preds = clusterer.predict(data_s)

centers = clusterer.means_

score = silhouette_score(data_s, preds)

print(score)

log_data['labels_sec']=preds
log_data

In [ ]:
data_t=log_dados.drop(['first','sec','for','fif','six'], axis = 1)

for n in range(2,40):
    
        clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_t)
        
        preds = clusterer.predict(data_t)

        centers = clusterer.means_

        score = silhouette_score(data_t, preds)

        if score > p:
            m = n
            p = score
        print('for n = %d:' %n)
        print(score)

In [ ]:
data_t=log_dados.drop(['first','sec','for','fif','six'], axis = 1)

clusterer = GMM(n_components = m, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_t)      
        
preds = clusterer.predict(data_t)

centers = clusterer.means_

score = silhouette_score(data_t, preds)

print(score)

log_data['labels_thi']=preds
log_data

In [ ]:
data_fo=log_dados.drop(['first','sec','thi','fif','six'], axis = 1)

for n in range(12,60):
    
        clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_fo)
        
        preds = clusterer.predict(data_fo)

        centers = clusterer.means_

        score = silhouette_score(data_fo, preds)

        if score > p:
            m = n
            p = score
        print('for n = %d:' %n)
        print(score)

In [ ]:
data_fo=log_dados.drop(['first','sec','thi','fif','six'], axis = 1)

clusterer = GMM(n_components = m, random_state = 42, covariance_type = 'tied', n_init = 500).fit(data_fo)

preds = clusterer.predict(data_fo)

centers = clusterer.means_

score = silhouette_score(data_fo, preds)

print(score)

log_data['labels_for']=preds
log_data

In [ ]:
data_fi=log_dados.drop(['first','sec','thi','for','six'], axis = 1)

for n in range(12,40):
    
        clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_fi)
        
        preds = clusterer.predict(data_fi)

        centers = clusterer.means_

        score = silhouette_score(data_fi, preds)
        
        if score > p:
            m = n
            p = score

        print('for n = %d:' %n)
        print(score)

In [ ]:
data_fi=log_dados.drop(['first','sec','thi','for','six'], axis = 1)

clusterer = GMM(n_components = m, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_fi)

preds = clusterer.predict(data_fi)

centers = clusterer.means_

score = silhouette_score(data_fi, preds)

print(score)

log_data['labels_fif']=preds
log_data

In [ ]:
data_si=log_dados.drop(['first','sec','thi','for','fif'], axis = 1)

for n in range(12,40):
    
    clusterer = GMM(n_components = n, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_si)
    
    preds = clusterer.predict(data_si)

    centers = clusterer.means_

    score = silhouette_score(data_si, preds)

    if score > p:
        m = n
        p = score

    print('for n = %d:' %n)
    print(score)

In [ ]:
data_si=log_dados.drop(['first','sec','thi','for','fif'], axis = 1)

clusterer = GMM(n_components = m, random_state = 42, covariance_type = 'tied', max_iter = 300, n_init = 500).fit(data_si)

preds = clusterer.predict(data_si)

centers = clusterer.means_

score = silhouette_score(data_si, preds)

print(score)

log_dados['labels_six']=preds
log_dados

In [ ]:
dataframe.to_csv('labeled_data.csv')

dataframe.to_csv('labeled_data.csv', encoding='utf-8')

In [ ]:
# log_data = pd.read_csv("labeled_data.csv")

# Somehow in my many trie outs i managed to get column labels with 0.95 of accuracy training on gmms and saved them in this labeled.csv file.
# Unfotunately I wasn't able to redo my tracks and never got the same accuracy again. But below it is and I tried to classify it using keras.

log_data = pd.read_csv("labeled.csv")

log_data.labels_first.max()

In [23]:
dataframe = log_data.drop('Unnamed: 0', axis = 1)
#labeling = 'labels_first'

sample = np.random.choice(dataframe[['concurso', 'labels_first']].index, size=int(len(dataframe)*0.9), replace=False)
train_data, test_data = dataframe[['concurso', 'labels_first']].iloc[sample], dataframe[['concurso', 'labels_first']].drop(sample)

print("Number of training samples is", len(train_data))
print("Number of testing samples is", len(test_data))
print(train_data[:10])
print(test_data[:10])

Number of training samples is 230
Number of testing samples is 26
     concurso  labels_first
170  7.593374             2
95   7.630461             2
41   7.656337             0
53   7.650645            18
58   7.648263             1
177  7.589842            18
44   7.654917            12
66   7.644441             7
36   7.658700             0
1    7.675082             1
    concurso  labels_first
2   7.674617             2
11  7.670429             6
15  7.668561             6
22  7.665285            10
23  7.664816             3
34  7.659643             0
46  7.653969             3
68  7.643483             6
71  7.642044             6
75  7.640123             1


In [28]:
import keras

# Separate data and one-hot encode the output
# Note: We're also turning the data into numpy arrays, in order to train the model in Keras
features = np.array(train_data.drop(['labels_first'], axis=1))
targets = np.array(keras.utils.to_categorical(train_data['labels_first'], 21))
features_test = np.array(test_data.drop(['labels_first'], axis=1))
targets_test = np.array(keras.utils.to_categorical(test_data['labels_first'], 21))

print(features[:10])
print(targets[:10])

[[7.59337419]
 [7.63046126]
 [7.65633717]
 [7.65064455]
 [7.64826303]
 [7.58984151]
 [7.65491705]
 [7.64444076]
 [7.65869956]
 [7.67508186]]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.utils import np_utils
from keras import optimizers

# Building the model
model = None
model = Sequential()
model.add(Dense(640, activation='tanh', input_shape=(1,)))
model.add(Dropout(.2))
model.add(Dense(320, activation='relu'))
model.add(Dropout(.2))
model.add(Dense(160, activation='relu'))
model.add(Dropout(.2))
model.add(Dense(80, activation='relu'))
model.add(Dropout(.1))
model.add(Dense(21, activation='softmax'))

# Compiling the model
model.compile(loss = 'binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

# The loss that predicts with the best accuracy is binary_crossentropy but when i used the trained model to predict the 2156's 'number' values for the 'first', 'second', 'third' columns, it won't give the right number and, in fact, it will predict the same number for all of them. I know which are the results for the 2156's despite they're not on the dataframe. 

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 640)               1280      
_________________________________________________________________
dropout_17 (Dropout)         (None, 640)               0         
_________________________________________________________________
dense_22 (Dense)             (None, 320)               205120    
_________________________________________________________________
dropout_18 (Dropout)         (None, 320)               0         
_________________________________________________________________
dense_23 (Dense)             (None, 160)               51360     
_________________________________________________________________
dropout_19 (Dropout)         (None, 160)               0         
_________________________________________________________________
dense_24 (Dense)             (None, 80)                12880     
__________

In [33]:
from keras.callbacks import ModelCheckpoint

checkpointer = ModelCheckpoint(filepath = 'MS.model.best.hdf5', verbose = 1, save_best_only = True)
model.fit(features, targets, validation_split = 0.2, callbacks = [checkpointer], epochs=300, batch_size=150, verbose=1)

Train on 184 samples, validate on 46 samples
Epoch 1/300
184/184 [==============================] - 1s 6ms/step - loss: 0.1933 - acc: 0.9524 - val_loss: 0.1835 - val_acc: 0.9524

Epoch 00001: val_loss improved from inf to 0.18346, saving model to MS.model.best.hdf5
Epoch 2/300
184/184 [==============================] - 0s 92us/step - loss: 0.1762 - acc: 0.9524 - val_loss: 0.1837 - val_acc: 0.9524

Epoch 00002: val_loss did not improve from 0.18346
Epoch 3/300
184/184 [==============================] - 0s 141us/step - loss: 0.1757 - acc: 0.9508 - val_loss: 0.1773 - val_acc: 0.9524

Epoch 00003: val_loss improved from 0.18346 to 0.17732, saving model to MS.model.best.hdf5
Epoch 4/300
184/184 [==============================] - 0s 168us/step - loss: 0.1741 - acc: 0.9506 - val_loss: 0.1726 - val_acc: 0.9524

Epoch 00004: val_loss improved from 0.17732 to 0.17261, saving model to MS.model.best.hdf5
Epoch 5/300
184/184 [==============================] - 0s 163us/step - loss: 0.1700 - acc: 0.9

184/184 [==============================] - 0s 168us/step - loss: 0.1625 - acc: 0.9524 - val_loss: 0.1721 - val_acc: 0.9524

Epoch 00043: val_loss did not improve from 0.16890
Epoch 44/300
184/184 [==============================] - 0s 379us/step - loss: 0.1638 - acc: 0.9524 - val_loss: 0.1717 - val_acc: 0.9524

Epoch 00044: val_loss did not improve from 0.16890
Epoch 45/300
184/184 [==============================] - 0s 168us/step - loss: 0.1618 - acc: 0.9524 - val_loss: 0.1716 - val_acc: 0.9524

Epoch 00045: val_loss did not improve from 0.16890
Epoch 46/300
184/184 [==============================] - 0s 260us/step - loss: 0.1627 - acc: 0.9524 - val_loss: 0.1720 - val_acc: 0.9524

Epoch 00046: val_loss did not improve from 0.16890
Epoch 47/300
184/184 [==============================] - 0s 201us/step - loss: 0.1621 - acc: 0.9524 - val_loss: 0.1725 - val_acc: 0.9524

Epoch 00047: val_loss did not improve from 0.16890
Epoch 48/300
184/184 [==============================] - 0s 201us/step - l

184/184 [==============================] - 0s 190us/step - loss: 0.1624 - acc: 0.9524 - val_loss: 0.1727 - val_acc: 0.9524

Epoch 00086: val_loss did not improve from 0.16890
Epoch 87/300
184/184 [==============================] - 0s 211us/step - loss: 0.1602 - acc: 0.9524 - val_loss: 0.1732 - val_acc: 0.9524

Epoch 00087: val_loss did not improve from 0.16890
Epoch 88/300
184/184 [==============================] - 0s 190us/step - loss: 0.1616 - acc: 0.9524 - val_loss: 0.1735 - val_acc: 0.9524

Epoch 00088: val_loss did not improve from 0.16890
Epoch 89/300
184/184 [==============================] - 0s 228us/step - loss: 0.1610 - acc: 0.9524 - val_loss: 0.1740 - val_acc: 0.9524

Epoch 00089: val_loss did not improve from 0.16890
Epoch 90/300
184/184 [==============================] - 0s 179us/step - loss: 0.1614 - acc: 0.9524 - val_loss: 0.1739 - val_acc: 0.9524

Epoch 00090: val_loss did not improve from 0.16890
Epoch 91/300
184/184 [==============================] - 0s 141us/step - l

184/184 [==============================] - 0s 211us/step - loss: 0.1620 - acc: 0.9524 - val_loss: 0.1756 - val_acc: 0.9524

Epoch 00129: val_loss did not improve from 0.16890
Epoch 130/300
184/184 [==============================] - 0s 168us/step - loss: 0.1615 - acc: 0.9524 - val_loss: 0.1758 - val_acc: 0.9524

Epoch 00130: val_loss did not improve from 0.16890
Epoch 131/300
184/184 [==============================] - 0s 119us/step - loss: 0.1633 - acc: 0.9524 - val_loss: 0.1756 - val_acc: 0.9524

Epoch 00131: val_loss did not improve from 0.16890
Epoch 132/300
184/184 [==============================] - 0s 125us/step - loss: 0.1625 - acc: 0.9524 - val_loss: 0.1754 - val_acc: 0.9524

Epoch 00132: val_loss did not improve from 0.16890
Epoch 133/300
184/184 [==============================] - 0s 125us/step - loss: 0.1625 - acc: 0.9524 - val_loss: 0.1746 - val_acc: 0.9524

Epoch 00133: val_loss did not improve from 0.16890
Epoch 134/300
184/184 [==============================] - 0s 157us/ste

184/184 [==============================] - 0s 130us/step - loss: 0.1627 - acc: 0.9524 - val_loss: 0.1729 - val_acc: 0.9524

Epoch 00172: val_loss did not improve from 0.16890
Epoch 173/300
184/184 [==============================] - 0s 136us/step - loss: 0.1626 - acc: 0.9524 - val_loss: 0.1733 - val_acc: 0.9524

Epoch 00173: val_loss did not improve from 0.16890
Epoch 174/300
184/184 [==============================] - 0s 130us/step - loss: 0.1613 - acc: 0.9524 - val_loss: 0.1738 - val_acc: 0.9524

Epoch 00174: val_loss did not improve from 0.16890
Epoch 175/300
184/184 [==============================] - 0s 168us/step - loss: 0.1622 - acc: 0.9524 - val_loss: 0.1740 - val_acc: 0.9524

Epoch 00175: val_loss did not improve from 0.16890
Epoch 176/300
184/184 [==============================] - 0s 228us/step - loss: 0.1629 - acc: 0.9524 - val_loss: 0.1741 - val_acc: 0.9524

Epoch 00176: val_loss did not improve from 0.16890
Epoch 177/300
184/184 [==============================] - 0s 163us/ste

184/184 [==============================] - 0s 103us/step - loss: 0.1607 - acc: 0.9524 - val_loss: 0.1745 - val_acc: 0.9524

Epoch 00215: val_loss did not improve from 0.16890
Epoch 216/300
184/184 [==============================] - 0s 108us/step - loss: 0.1600 - acc: 0.9524 - val_loss: 0.1741 - val_acc: 0.9524

Epoch 00216: val_loss did not improve from 0.16890
Epoch 217/300
184/184 [==============================] - 0s 130us/step - loss: 0.1615 - acc: 0.9524 - val_loss: 0.1739 - val_acc: 0.9524

Epoch 00217: val_loss did not improve from 0.16890
Epoch 218/300
184/184 [==============================] - 0s 282us/step - loss: 0.1612 - acc: 0.9524 - val_loss: 0.1742 - val_acc: 0.9524

Epoch 00218: val_loss did not improve from 0.16890
Epoch 219/300
184/184 [==============================] - 0s 255us/step - loss: 0.1612 - acc: 0.9524 - val_loss: 0.1750 - val_acc: 0.9524

Epoch 00219: val_loss did not improve from 0.16890
Epoch 220/300
184/184 [==============================] - 0s 201us/ste

184/184 [==============================] - 0s 136us/step - loss: 0.1605 - acc: 0.9524 - val_loss: 0.1745 - val_acc: 0.9524

Epoch 00258: val_loss did not improve from 0.16890
Epoch 259/300
184/184 [==============================] - 0s 228us/step - loss: 0.1615 - acc: 0.9524 - val_loss: 0.1747 - val_acc: 0.9524

Epoch 00259: val_loss did not improve from 0.16890
Epoch 260/300
184/184 [==============================] - 0s 195us/step - loss: 0.1621 - acc: 0.9524 - val_loss: 0.1745 - val_acc: 0.9524

Epoch 00260: val_loss did not improve from 0.16890
Epoch 261/300
184/184 [==============================] - 0s 179us/step - loss: 0.1612 - acc: 0.9524 - val_loss: 0.1741 - val_acc: 0.9524

Epoch 00261: val_loss did not improve from 0.16890
Epoch 262/300
184/184 [==============================] - 0s 190us/step - loss: 0.1614 - acc: 0.9524 - val_loss: 0.1736 - val_acc: 0.9524

Epoch 00262: val_loss did not improve from 0.16890
Epoch 263/300
184/184 [==============================] - 0s 184us/ste

In [34]:
score = model.evaluate(features, targets)

print("\n Training Accuracy:", score[1])

score = model.evaluate(features_test, targets_test)
print("\n Testing Accuracy:", score[1])


230/230 [==============================] - 0s 48us/step

 Training Accuracy: 0.9523810132690098
26/26 [==============================] - 0s 77us/step

 Testing Accuracy: 0.9523810148239136


In [35]:
df1 = np.array([[2160, ]])
df1


array([[2160]])

In [36]:
model.predict_classes(
    x=df1,
    batch_size=60,
    verbose=0,
    )

array([1], dtype=int64)

In [37]:
sample = np.random.choice(log_data[['concurso', 'first', 'labels_first']].index, size=int(len(log_data)*0.9), replace=False)
train_data, test_data = log_data[['concurso', 'first', 'labels_first']].iloc[sample], log_data[['concurso', 'first', 'labels_first']].drop(sample)

print("Number of training samples is", len(train_data))
print("Number of testing samples is", len(test_data))
print(train_data[:10])
print(test_data[:10])

Number of training samples is 230
Number of testing samples is 26
     concurso     first  labels_first
6    7.672758  3.044522             6
69   7.643004  1.386294             3
72   7.641564  4.025352            12
13   7.669495  3.784190             0
135  7.610853  0.693147            17
160  7.598399  2.639057             6
201  7.577634  3.688879             1
27   7.662938  3.178054            10
84   7.635787  3.555348             0
204  7.576097  4.007333             1
    concurso     first  labels_first
3   7.674153  3.891820             0
14  7.669028  2.302585             8
15  7.668561  2.995732             6
22  7.665285  3.258097            10
28  7.662468  1.945910            14
45  7.654443  3.218876             4
48  7.653020  3.912023             1
67  7.643962  3.178054             5
80  7.637716  1.945910            14
82  7.636752  4.007333             1


In [38]:
import keras

# Separate data and one-hot encode the output
# Note: We're also turning the data into numpy arrays, in order to train the model in Keras
features = np.array(train_data.drop(['first'], axis=1))
targets = np.array(keras.utils.to_categorical(train_data['first'], 60))
features_test = np.array(test_data.drop(['first'], axis=1))
targets_test = np.array(keras.utils.to_categorical(test_data['first'], 60))

print(features[:10])
print(targets[:10])

[[ 7.6727579   6.        ]
 [ 7.64300364  3.        ]
 [ 7.64156444 12.        ]
 [ 7.66949525  0.        ]
 [ 7.61085279 17.        ]
 [ 7.59839933  6.        ]
 [ 7.57763383  1.        ]
 [ 7.66293785 10.        ]
 [ 7.63578686  0.        ]
 [ 7.57609734  1.        ]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 

In [42]:
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.utils import np_utils
from keras import optimizers

# Building the model
model = None
model = Sequential()
model.add(Dense(512, activation='tanh', input_shape=(2,)))
model.add(Dropout(.2))
model.add(Dense(256, activation='relu'))
model.add(Dropout(.2))
model.add(Dense(128, activation='tanh'))
model.add(Dropout(.1))
model.add(Dense(60, activation='softmax'))

# Compiling the model
model.compile(loss = 'mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_34 (Dense)             (None, 512)               1536      
_________________________________________________________________
dropout_27 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_35 (Dense)             (None, 256)               131328    
_________________________________________________________________
dropout_28 (Dropout)         (None, 256)               0         
_________________________________________________________________
dense_36 (Dense)             (None, 128)               32896     
_________________________________________________________________
dropout_29 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_37 (Dense)             (None, 60)                7740      
Total para

In [43]:
checkpointer2 = ModelCheckpoint(filepath = 'MS2.model.best.hdf5', verbose = 1, save_best_only = True)
model.fit(features, targets, validation_split = 0.2, callbacks = [checkpointer2], epochs=200, batch_size=50, verbose=1)

Train on 184 samples, validate on 46 samples
Epoch 1/200
184/184 [==============================] - 1s 5ms/step - loss: 0.0153 - acc: 0.2880 - val_loss: 0.0122 - val_acc: 0.5435

Epoch 00001: val_loss improved from inf to 0.01218, saving model to MS2.model.best.hdf5
Epoch 2/200
184/184 [==============================] - 0s 130us/step - loss: 0.0127 - acc: 0.5326 - val_loss: 0.0115 - val_acc: 0.5435

Epoch 00002: val_loss improved from 0.01218 to 0.01149, saving model to MS2.model.best.hdf5
Epoch 3/200
184/184 [==============================] - 0s 146us/step - loss: 0.0116 - acc: 0.5054 - val_loss: 0.0107 - val_acc: 0.5000

Epoch 00003: val_loss improved from 0.01149 to 0.01068, saving model to MS2.model.best.hdf5
Epoch 4/200
184/184 [==============================] - 0s 146us/step - loss: 0.0115 - acc: 0.4728 - val_loss: 0.0098 - val_acc: 0.5435

Epoch 00004: val_loss improved from 0.01068 to 0.00984, saving model to MS2.model.best.hdf5
Epoch 5/200
184/184 [============================

184/184 [==============================] - 0s 488us/step - loss: 0.0079 - acc: 0.6304 - val_loss: 0.0060 - val_acc: 0.6739

Epoch 00041: val_loss improved from 0.00635 to 0.00602, saving model to MS2.model.best.hdf5
Epoch 42/200
184/184 [==============================] - 0s 369us/step - loss: 0.0079 - acc: 0.6196 - val_loss: 0.0063 - val_acc: 0.6739

Epoch 00042: val_loss did not improve from 0.00602
Epoch 43/200
184/184 [==============================] - 0s 455us/step - loss: 0.0078 - acc: 0.6304 - val_loss: 0.0067 - val_acc: 0.6957

Epoch 00043: val_loss did not improve from 0.00602
Epoch 44/200
184/184 [==============================] - 0s 298us/step - loss: 0.0078 - acc: 0.6576 - val_loss: 0.0065 - val_acc: 0.6739

Epoch 00044: val_loss did not improve from 0.00602
Epoch 45/200
184/184 [==============================] - 0s 347us/step - loss: 0.0084 - acc: 0.5598 - val_loss: 0.0061 - val_acc: 0.6739

Epoch 00045: val_loss did not improve from 0.00602
Epoch 46/200
184/184 [==========

Epoch 82/200
184/184 [==============================] - 0s 358us/step - loss: 0.0062 - acc: 0.7609 - val_loss: 0.0053 - val_acc: 0.8043

Epoch 00082: val_loss did not improve from 0.00446
Epoch 83/200
184/184 [==============================] - 0s 271us/step - loss: 0.0067 - acc: 0.6685 - val_loss: 0.0053 - val_acc: 0.7609

Epoch 00083: val_loss did not improve from 0.00446
Epoch 84/200
184/184 [==============================] - 0s 244us/step - loss: 0.0060 - acc: 0.7391 - val_loss: 0.0051 - val_acc: 0.7609

Epoch 00084: val_loss did not improve from 0.00446
Epoch 85/200
184/184 [==============================] - 0s 325us/step - loss: 0.0062 - acc: 0.7337 - val_loss: 0.0046 - val_acc: 0.7826

Epoch 00085: val_loss did not improve from 0.00446
Epoch 86/200
184/184 [==============================] - 0s 304us/step - loss: 0.0064 - acc: 0.7337 - val_loss: 0.0045 - val_acc: 0.7609

Epoch 00086: val_loss did not improve from 0.00446
Epoch 87/200
184/184 [==============================] - 0s 4

184/184 [==============================] - 0s 271us/step - loss: 0.0054 - acc: 0.7337 - val_loss: 0.0043 - val_acc: 0.7609

Epoch 00125: val_loss improved from 0.00436 to 0.00434, saving model to MS2.model.best.hdf5
Epoch 126/200
184/184 [==============================] - 0s 282us/step - loss: 0.0052 - acc: 0.7554 - val_loss: 0.0045 - val_acc: 0.7826

Epoch 00126: val_loss did not improve from 0.00434
Epoch 127/200
184/184 [==============================] - 0s 336us/step - loss: 0.0054 - acc: 0.7609 - val_loss: 0.0045 - val_acc: 0.7826

Epoch 00127: val_loss did not improve from 0.00434
Epoch 128/200
184/184 [==============================] - 0s 369us/step - loss: 0.0055 - acc: 0.7283 - val_loss: 0.0050 - val_acc: 0.6957

Epoch 00128: val_loss did not improve from 0.00434
Epoch 129/200
184/184 [==============================] - 0s 266us/step - loss: 0.0059 - acc: 0.6957 - val_loss: 0.0045 - val_acc: 0.7609

Epoch 00129: val_loss did not improve from 0.00434
Epoch 130/200
184/184 [=====

184/184 [==============================] - 0s 152us/step - loss: 0.0050 - acc: 0.7880 - val_loss: 0.0049 - val_acc: 0.7609

Epoch 00167: val_loss did not improve from 0.00398
Epoch 168/200
184/184 [==============================] - 0s 504us/step - loss: 0.0052 - acc: 0.7880 - val_loss: 0.0053 - val_acc: 0.7391

Epoch 00168: val_loss did not improve from 0.00398
Epoch 169/200
184/184 [==============================] - 0s 287us/step - loss: 0.0054 - acc: 0.7609 - val_loss: 0.0050 - val_acc: 0.7391

Epoch 00169: val_loss did not improve from 0.00398
Epoch 170/200
184/184 [==============================] - 0s 298us/step - loss: 0.0054 - acc: 0.7283 - val_loss: 0.0046 - val_acc: 0.7826

Epoch 00170: val_loss did not improve from 0.00398
Epoch 171/200
184/184 [==============================] - 0s 282us/step - loss: 0.0048 - acc: 0.7772 - val_loss: 0.0046 - val_acc: 0.8043

Epoch 00171: val_loss did not improve from 0.00398
Epoch 172/200
184/184 [==============================] - 0s 260us/ste

In [44]:
df1 = np.array([[np.log(2159), 1]])
df1

array([[7.67740043, 1.        ]])

In [46]:
model.predict_classes(
    x=df1,
    batch_size=200,
    verbose=0,
)

array([3], dtype=int64)

In [ ]:
# wanted to tyr out the code below but couldn't make it run without errors

import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.utils import np_utils
from keras.optimizers import *
import talos as ta
from keras.activations import *
from keras.losses import binary_crossentropy, categorical_crossentropy
from talos.metrics.keras_metrics import fmeasure_acc

params = {'lr':[0.001,0.01,0.02,0.03,0.1,0.2],
     'first_neuron':[512],    
     'batch_size': [30, 50, 80, 100, 120],
     'epochs': [100, 200, 300],
     'dropout': [0.1, 0.2, 0.3],
     'kernel_initializer': ['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform'],
     'optimizer': [Nadam, Adam, RMSprop],
     'losses': [binary_crossentropy, categorical_crossentropy],
     'activation':['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear'],
     'last_activation': ['sigmoid']}

def breast_cancer_model(features, target, features_test, target_test, params):
    
 
    model = Sequential()

    model.add(Dense(params['first_neuron'], input_shape=(2,),
                    activation=params['activation'],
                    kernel_initializer=params['kernel_initializer']))

    model.add(Dropout(params['dropout']))

    model.add(Dense(256, activation=params['activation'], kernel_initializer=params['kernel_initializer']))
    model.add(Dropout(params['dropout']))

    model.add(Dense(128, activation=params['activation'], kernel_initializer=params['kernel_initializer']))
    model.add(Dropout(params['dropout']))
    
    model.add(Dense(64, activation=params['activation'], kernel_initializer=params['kernel_initializer']))
    model.add(Dropout(params['dropout']))
    
    model.add(Dense(21, activation=params['last_activation'], kernel_initializer=params['kernel_initializer']))

    model.compile(loss=params['losses'], optimizer=params['optimizer'](lr=params['lr']), metrics=['acc', fmeasure_acc])
        
    model.summary()
        
    history = model.fit(features, targets, epochs=params['epochs'], batch_size=params['batch_size'], verbose=0)
    score = model.evaluate(features, targets)
        
    print("\n Training Accuracy:", score[1])
    score = model.evaluate(features_test, targets_test)
    print("\n Testing Accuracy:", score[1])
    
    return history, model

print(len(features))
t = ta.Scan(x=features,
            y=targets,
            model=breast_cancer_model,
            params=params,
            dataset_name='breast_cancer',
            experiment_no='1')

In [ ]:
## Challenge: Play with the parameters!
#You can see that we made several decisions in our training. For instance, the number of layers, the sizes of the layers, the number of epochs, etc.
#It's your turn to play with parameters! Can you improve the accuracy? The following are other suggestions for these parameters. We'll learn the definitions later in the class:
# - Activation function: relu and sigmoid
# - Loss function: categorical_crossentropy, mean_squared_error
# - Optimizer: rmsprop, adam, ada